[build]
  # Specifies the build command to generate your site's static files.
  # If you have a build script defined in your package.json, use that command here.
  command = "npm run build" 
  # Specifies the directory that contains your static files for deployment.
  publish = "build" # Adjust this path to where your build script outputs the files.
